version: '3'

services:
    hierarchical_3d_gaussians:
        container_name: hierarchical_3d_gaussians
        # !IMPORTANT! Use `image` if pulling from ghcr. Use `build` if building locally!
        image: ghcr.io/fabulani/hierarchical-3d-gaussians:latest
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ${PWD}:/host
            - ./data/:/data
        ports:
            - "6009:6009"
        ipc: host
        extra_hosts:
            - "host.docker.internal:host-gateway"
        entrypoint: ["/entrypoint.sh"]
        command: ["bash"]
        networks:
            - main

networks:
    main:
        driver: bridge